product/urls.py
from django.urls import path
app_name = 'product'

from .views import ProductList,ProductDetail,BrandList,Brand_Detail, query_Debug, add_review

from .api import productlist_api, ProductListApi, ProducDetailApi, BrandListApi, BrandDetailApi




urlpatterns = [
    path('debug', query_Debug , name='query_debug'),
    path('' , ProductList.as_view(), name='product_list'),
    path('<slug:slug>' , ProductDetail.as_view() , name='product_detail'),
    path('<slug:slug>/add_review' , add_review, name='add_review'),
    path('brands/',BrandList.as_view(), name ='brand_list'),
    path('brands/<slug:slug>',Brand_Detail.as_view(), name ='brand_detail'),



#api urls
# path('api/list',productlist_api, name='product list'),
path('api/list', ProductListApi.as_view(), name='product list'),
path('api/list/brands', BrandListApi.as_view(), name='brand list'),
path('api/list/brands/<slug:slug>' , BrandDetailApi.as_view(), name='brand detail'),
path('api/list/<slug:slug>' , ProducDetailApi.as_view(), name='product detail'),




]

src/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('products/', include('product.urls', namespace='products')),
    path('orders/', include('orders.urls', namespace='orders')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('', include('settings.urls', namespace='settings')),
    path('api-auth/', include('rest_framework.urls')),


    re_path(r'^rosetta/', include('rosetta.urls')),  # library for translation models ---url

    path("i18n/", include("django.conf.urls.i18n")),
]

urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models
from taggit.managers import TaggableManager
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.db.models.aggregates import  Avg


# Create your models here.

PRODUCT_FLAG =(
    ('Sale','Sales'),
    ('Feature','Feature'),
    ('New','New'),

)
class Product(models.Model):

    name = models.CharField(_('name'),max_length=150)
    image = models.ImageField(_('image'),upload_to='products/', default='default.png')
    flag = models.CharField(_('flag'),max_length=10,choices=PRODUCT_FLAG)
    price = models.FloatField(_('price'))
    sku = models.IntegerField(_('sku'))
    brand = models.ForeignKey('Brand',verbose_name=('brand'),related_name='product_brand',on_delete=models.CASCADE)
    tags = TaggableManager()
    subtitle = models.TextField(_('subtitle'),max_length=500)
    description = models.TextField(_('description'),max_length=2800)
    quantity = models.IntegerField()
    slug= models.SlugField(null=True,blank=True)

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)
    
    def get_avg_rate(self):
        avg= self.product_review.aggregate(rate_avg=Avg('rate'))
        return avg

    
    
    






class ProductImages(models.Model):
    product =models.ForeignKey(Product,verbose_name=_('product'),related_name='product_image',on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product_images/')
    
    
    def __str__(self):
        return str(self.product)
    

 


class Brand(models.Model):
    name = models.CharField(_('brand'),max_length=50)
    image = models.ImageField(_('image'),upload_to='brand/')
    slug = models.SlugField(null=True,blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Brand, self).save(*args, **kwargs)

    def __str__(self):
        return self.name
    


class Reviews(models.Model):
    user=models.ForeignKey(User, verbose_name=_('user'),related_name='review_author', on_delete=models.SET_NULL,null=True,blank=True)
    product =models.ForeignKey(Product,verbose_name=_('product'),related_name='product_review',on_delete=models.CASCADE)
    comment= models.CharField(_('comment'),max_length=200)
    rate = models.IntegerField(_('rate'))
    created_at= models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.product)
    

product/forms.py
from django import forms
from .models import Reviews


class ProductReviewForm(forms.ModelForm):
    class Meta:
        model = Reviews
        fields = ['comment', 'rate']

product/views.py
from typing import Any
from django.shortcuts import render, redirect
from django.views.generic import ListView , DetailView
from django.db.models import Count
from .models import Product , Brand, Reviews
from django.db.models import Q, F, Value, Func, ExpressionWrapper, DecimalField , FloatField
from django.db.models.aggregates import Sum , Avg, Min , Max , Count
from django.db.models.functions import Concat
from .forms import ProductReviewForm
from django.http import JsonResponse
from django.template.loader import render_to_string

# Q when we use (and, or) for serach lookup
# F when say the value of column = value of another column (price(value) = quantity(value))


def query_Debug(request):
    # data = Product.objects.filter(name__contains='Noah',price__gt=70)
    # data = Product.objects.filter(Q(name__contains='Noah') & Q(price__gt=20))
    # data = Product.objects.filter(price = F('quantity')) F mean Reference 
    # data = Product.objects.filter(price__gt=70).order_by('name').reverse()
    # data = Product.objects.order_by('name')
    # data = Product.objects.earliest('name')
    # data = Product.objects.latest('name')
    # data = Product.objects.values('name','id','price') --- fields that we want to appear in template 
    # data = Product.objects.values_list('name','id','brand__name')
    # data = Product.objects.prefetch_related('brand').all() used with many ot many 
    # data = Product.objects.select_related('brand').all() used with one to one and freignkey
    # data = Product.objects.aggregate(min_price=Min('price'),avg_price=Avg('price'))
    # data = Product.objects.annotate(is_new=F('quantity')*2) add column for counting
    # data = Product.objects.annotate(full_name =Concat('name',Value(' '),'flag'))
    dis_price=ExpressionWrapper(F('price')*.8, output_field=DecimalField())
    data = Product.objects.annotate(discounted_price=dis_price)
    

    return render(request,'product/productlist.html',{'data': data})





class ProductList(ListView):
    model = Product 
    paginate_by = 50


class ProductDetail(DetailView):
    model = Product 
    def get_context_data(self, **kwargs): 
        context = super().get_context_data(**kwargs)
        context["reviews"] = Reviews.objects.filter(product=self.get_object())
        return context
    
    

def add_review(request,slug):
    product= Product.objects.get(slug=slug)
    if request.method == 'POST':
        form = ProductReviewForm(request.POST)
        if form.is_valid():
            myform= form.save(commit=False)
            myform.user = request.user
            myform.product = product
            myform.save()

    reviews= Reviews.objects.filter(product=product)
    html = render_to_string('include/all_reviews.html',{'reviews':reviews, request:request})


    
    return JsonResponse({'result':html})


class BrandList(ListView):
    model = Brand
    paginate_by = 50

    queryset = Brand.objects.all().annotate(product_count= Count('product_brand'))


class Brand_Detail(ListView):
    model = Product
    paginate_by = 50
    template_name = 'product/brand_detail.html'
    

    # queryset = Brand.objects.filter(slug=slug).annotate(product_count= Count('product_brand'))
    def get_queryset(self):
        brand = Brand.objects.get(slug=self.kwargs['slug'])
        queryset = Product.objects.filter(brand=brand)
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # context["brand"] = Brand.objects.filter(slug=self.kwargs['slug']).annotate(product_count= Count('product_brand'))

        data = Brand.objects.filter(slug=self.kwargs['slug']).annotate(product_count= Count('product_brand'))[0]
        print(f"Brand : {data.name}")
        print(f"Brand : {data.image}")
        context["brand"] = data
        return context

product/templates/product/brand_list.html
{% extends "base.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'en/css/brand-list.css' %} ">
{% endblock css %}
{% block body %}
        <!--=====================================
                    BANNER PART START
        =======================================-->
        <section class="inner-section single-banner" style="background: url(images/single-banner.jpg) no-repeat center;">
            <div class="container">
                <h2>brand list</h2>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">brand-list</li>
                </ol>
            </div>
        </section>
        <!--=====================================
                    BANNER PART END
        =======================================-->


        <!--=====================================
                    BRAND LIST PART START
        =======================================-->
        <section class="inner-section">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="top-filter">
                            <div class="filter-show">
                                <label class="filter-label">Show :</label>
                                <select class="form-select filter-select">
                                    <option value="1">12</option>
                                    <option value="2">24</option>
                                    <option value="3">36</option>
                                </select>
                            </div>
                            <div class="filter-short">
                                <label class="filter-label">Short by :</label>
                                <select class="form-select filter-select isotope-select">
                                    <option value="*">show all</option>
                                    <option value=".vegetables">vegetables</option>
                                    <option value=".fruits">fruits</option>
                                    <option value=".drinks">drinks</option>
                                    <option value=".fishes">fishes</option>
                                    <option value=".meats">meats</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row-cols-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5 isotope-items">

                    {% for object in object_list %}
                        <div class="col all vegetables">
                            <div class="brand-wrap">
                                <div class="brand-media">
                                    <img src="{{object.image.url}}" alt="brand">
                                    <div class="brand-overlay">
                                        <a href="{% url 'products:brand_detail' object.slug %}"><i class="fas fa-link"></i></a>
                                    </div>
                                </div>
                                <div class="brand-meta">
                                    <h4>{{object}}</h4>
                                    <p>({{object.product_count}} items)</p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                </div>
                {% if is_paginated %}
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="bottom-paginate">
                                <p class="page-info">Showing 12 of 60 Results</p>
                                <ul class="pagination">
                                    {% if page_obj.has_previous %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                                                <i class="fas fa-long-arrow-alt-left"></i>
                                            </a>
                                        </li>
                                    {% endif %}
                                    {% for i in paginator.page_range %}
                                        {% if page_obj.number == i %}
                                            <li class="page-item"><a class="page-link active" href="#">{{ i }}</a></li>
                                        {% else %}
                                            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                        {% endif %}
                                    {% endfor %}
                                    {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                                                <i class="fas fa-long-arrow-alt-right"></i>
                                            </a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </section>
        <!--=====================================
                    BRAND LIST PART END
        =======================================-->


{% endblock body %}

product/templates/product/product_list.html
{% extends 'base.html' %}


{% block body %}



        <!--=====================================
                    BANNER PART START
        =======================================-->
        <section class="inner-section single-banner" style="background: url(images/single-banner.jpg) no-repeat center;">
            <div class="container">
                <h2>Shop 5 Column</h2>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">shop-5column</li>
                </ol>
            </div>
        </section>
        <!--=====================================
                    BANNER PART END
        =======================================-->


        <!--=====================================
                    SHOP PART START
        =======================================-->
        <section class="inner-section shop-part">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="top-filter">
                            <div class="filter-show">
                                <label class="filter-label">Show :</label>
                                <select class="form-select filter-select">
                                    <option value="1">12</option>
                                    <option value="2">24</option>
                                    <option value="3">36</option>
                                </select>
                            </div>
                            <div class="filter-short">
                                <label class="filter-label">Short by :</label>
                                <select class="form-select filter-select">
                                    <option selected>default</option>
                                    <option value="3">trending</option>
                                    <option value="1">featured</option>
                                    <option value="2">recommend</option>
                                </select>
                            </div>
                            <div class="filter-action">
                                <a href="shop-3column.html" title="Three Column"><i class="fas fa-th"></i></a>
                                <a href="shop-2column.html" title="Two Column"><i class="fas fa-th-large"></i></a>
                                <a href="shop-1column.html" title="One Column"><i class="fas fa-th-list"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row-cols-2 row-cols-md-3 row-cols-lg-3 row-cols-xl-5">
                    
                    {% for product in object_list  %}
                        <div class="col">
                            <div class="product-card">
                                <div class="product-media">
                                    <div class="product-label">
                                        <label class="label-text new">{{product.flag}}</label>
                                    </div>
                                    <button class="product-wish wish">
                                        <i class="fas fa-heart"></i>
                                    </button>
                                    <a class="product-image" href="product-video.html">
                                        <img style="width:203px; height:148px;" src="{{product.image.url}}" alt="product" >   
                                    </a>
                                    <div class="product-widget">
                                        <a title="Product Compare" href="compare.html" class="fas fa-random"></a>
                                        <a title="Product Video" href="https://youtu.be/9xzcVxSBbG8" class="venobox fas fa-play" data-autoplay="true" data-vbtype="video"></a>
                                        <a title="Product View" href="#" class="fas fa-eye" data-bs-toggle="modal" data-bs-target="#product-view"></a>
                                    </div>
                                </div>
                                <div class="product-content">
                                    <div class="product-rating">
                                        <i class=" icofont-star {% if product.get_avg_rate.rate_avg > 0 %} active {% endif%} "></i>
                                        <i class=" icofont-star {% if product.get_avg_rate.rate_avg > 1 %} active {% endif%} "></i>
                                        <i class=" icofont-star {% if product.get_avg_rate.rate_avg > 2 %} active {% endif%} "></i>
                                        <i class=" icofont-star {% if product.get_avg_rate.rate_avg > 3 %} active {% endif%} "></i>
                                        <i class=" icofont-star {% if product.get_avg_rate.rate_avg > 4 %} active {% endif%} "></i>
                                        <a href="product-video.html">({{product.product_review.all|length}})</a>
                                        <p>{{product.get_avg_rate.rate_avg}} </p>
                                    </div>
                                    <h6 class="product-name">
                                        <a href="{% url 'products:product_detail' product.slug %}">{{product}}</a>
                                    </h6>
                                    <h6 class="product-price">
                                        <del>$34</del>
                                        <span>${{product.price}}<small>/piece</small></span>
                                    </h6>
                                    <button class="product-add" title="Add to Cart">
                                        <i class="fas fa-shopping-basket"></i>
                                        <span>add</span>
                                    </button>
                                    <div class="product-action">
                                        <button class="action-minus" title="Quantity Minus"><i class="icofont-minus"></i></button>
                                        <input class="action-input" title="Quantity Number" type="text" name="quantity" value="1">
                                        <button class="action-plus" title="Quantity Plus"><i class="icofont-plus"></i></button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}


                </div>
                {% if is_paginated %}
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="bottom-paginate">
                                <p class="page-info">Showing 12 of 60 Results</p>
                                <ul class="pagination">
                                    {% if page_obj.has_previous %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                                                <i class="fas fa-long-arrow-alt-left"></i>
                                            </a>
                                        </li>
                                    {% endif %}
                                    {% for i in paginator.page_range %}
                                        {% if page_obj.number == i %}
                                            <li class="page-item"><a class="page-link active" href="#">{{ i }}</a></li>
                                        {% else %}
                                            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                        {% endif %}
                                    {% endfor %}
                                    {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                                                <i class="fas fa-long-arrow-alt-right"></i>
                                            </a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </section>
        <!--=====================================
                    SHOP PART END
        =======================================-->
        
        
{% endblock body %}

product/templates/product/productlist.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1> Debug </h1>
        
        
    <ul>
        {% for item in data %}
            <li>{{item}}  </li>
        {% endfor %}

    </ul> 





</body>
</html>